In [3]:
my_list =[1,2,3]
my_list

[1, 2, 3]

In [4]:
import numpy as np

In [6]:
arr=np.array(my_list)

In [7]:
#1-d array
arr

array([1, 2, 3])

In [10]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
#2-d array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
#an array of all zeros
np.zeros(4)

array([0., 0., 0., 0.])

In [15]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
#array of pure ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
#evenly spaced points
#note its 1-d
np.linspace(0,5,60)

array([0.        , 0.08474576, 0.16949153, 0.25423729, 0.33898305,
       0.42372881, 0.50847458, 0.59322034, 0.6779661 , 0.76271186,
       0.84745763, 0.93220339, 1.01694915, 1.10169492, 1.18644068,
       1.27118644, 1.3559322 , 1.44067797, 1.52542373, 1.61016949,
       1.69491525, 1.77966102, 1.86440678, 1.94915254, 2.03389831,
       2.11864407, 2.20338983, 2.28813559, 2.37288136, 2.45762712,
       2.54237288, 2.62711864, 2.71186441, 2.79661017, 2.88135593,
       2.96610169, 3.05084746, 3.13559322, 3.22033898, 3.30508475,
       3.38983051, 3.47457627, 3.55932203, 3.6440678 , 3.72881356,
       3.81355932, 3.89830508, 3.98305085, 4.06779661, 4.15254237,
       4.23728814, 4.3220339 , 4.40677966, 4.49152542, 4.57627119,
       4.66101695, 4.74576271, 4.83050847, 4.91525424, 5.        ])

In [32]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
#random numbers and methods
np.random.rand(4)

array([0.60421834, 0.09322282, 0.26294068, 0.8547736 ])

In [36]:
np.random.rand(4,5)
#note this is 2-d

array([[0.18413214, 0.89476044, 0.01472326, 0.15645957, 0.57329092],
       [0.82989486, 0.73768707, 0.41252818, 0.49487051, 0.97277269],
       [0.23487061, 0.85338454, 0.34607222, 0.6356445 , 0.24653059],
       [0.83807375, 0.94314211, 0.87838892, 0.63647321, 0.53001617]])

In [39]:
np.random.randn(5)

array([-0.04498674,  1.41889352,  0.14396526, -0.54807573, -0.00182773])

In [40]:
np.random.randn(5,5)

array([[-2.09142705,  0.73831699,  0.55596457, -1.32799458, -0.61172359],
       [ 0.31231879, -1.44284112, -1.17174272, -1.46663245, -0.79510792],
       [ 1.1550926 , -1.39678984,  0.21876159,  0.45986886,  0.14685391],
       [-0.37155536, -1.47256196, -0.45712666, -0.50899038,  1.23813008],
       [ 0.25223864, -0.78840873, -0.557697  ,  2.49657938,  0.0130081 ]])

In [41]:
np.random.randn(2,2,2)
#3-d

array([[[ 0.69667051, -1.21717212],
        [-1.02837304, -0.13595979]],

       [[-1.78234702,  0.73803523],
        [-0.05856348,  1.12078708]]])

In [49]:
np.random.randint(0,10,5)
#random integers
#note the low is inclusive and the high is exclusive

array([8, 2, 5, 2, 7])

In [50]:
#METHODS IN AN ARRAY

In [52]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
ranarr= np.random.randint(0,50,10)
ranarr

array([ 5, 15, 39, 21, 24, 36, 26, 15, 26, 30])

In [55]:
#reshape

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
#note when using reshape you will get an error if you can't fill up the matrix completely
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

In [60]:
#max , min, index

In [61]:
ranarr

array([ 5, 15, 39, 21, 24, 36, 26, 15, 26, 30])

In [64]:
ranarr.max

<function ndarray.max>

In [66]:
ranarr.max()

39

In [67]:
ranarr.min()

5

In [68]:
ranarr.argmax() #index location

2

In [69]:
ranarr.argmin()

0

In [71]:
#how to figure out the shape of a vector
arr.shape

(25,)

In [72]:
#size of a vector
arr.size

25

In [73]:
#data type in an array
arr.dtype

dtype('int32')

In [74]:
ranarr.dtype

dtype('int32')

In [75]:
from numpy.random import randint

In [76]:
randint(1,40,10)

array([27, 31, 26, 33, 17, 12,  3, 37, 33, 23])

In [77]:
#NUMPY ARRAY INDEXING

In [81]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
arr[0]

1

In [83]:
arr[1:5]

array([2, 3, 4, 5])

In [84]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [85]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [86]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [90]:
#numpy arrays can broadcast


In [91]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [92]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [93]:
#note the broadcast is permanent

In [94]:
arr = np.arange(1,11)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [96]:
slice_of_arr = arr[0:6]

In [97]:
slice_of_arr

array([1, 2, 3, 4, 5, 6])

In [98]:
slice_of_arr[:]= 99

In [99]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [100]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [101]:
#note it has also changed to the original arr


In [102]:
#you can specificaly specify copy

In [109]:
arr_copy =arr.copy()

In [104]:
arr_copy

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [105]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [106]:
arr_copy[:]= 100

In [107]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [108]:
arr

array([99, 99, 99, 99, 99, 99,  7,  8,  9, 10])

In [110]:
#indexing a 2-d or a matrix

In [111]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [112]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [113]:
arr_2d[0][0]

5

In [115]:
arr_2d[0][2]

15

In [116]:
arr_2d[2][0]

35

In [118]:
arr_2d[1,1]
#single bracket notation

25

In [119]:
arr_2d[2,2]

45

In [120]:
arr_2d[:2, 1:]
#grabing subsections

array([[10, 15],
       [25, 30]])

In [122]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [123]:
#conditional selection

In [126]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [129]:
bool_arr = arr > 5

In [130]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [131]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [132]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [139]:
arr[arr<=5]

array([1, 2, 3, 4, 5])

In [140]:
arr_2d = np.arange(50).reshape(5,10)

In [141]:
arr_2d


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [145]:
arr_2d[2:-1, 3:6]

array([[23, 24, 25],
       [33, 34, 35]])

In [146]:
arr_2d[arr_2d > 24]

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49])

In [2]:
#NUMPY OPERATIONS

In [3]:
 import numpy as np
    

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [9]:
#note it occurs element by element basis

In [10]:
arr + 100
#scalar operation

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [12]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [14]:
 arr / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [15]:
1 /0
#note the ZeroDivisionError, numpy won't issue this error

ZeroDivisionError: division by zero

In [17]:
arr / arr
#note the first value in arr is 0

C:\Users\Francis Maina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
#note it gives a nan when you divide a number by zero

In [20]:
1 / arr
#note if its another number divided by zero, you get an infinity back

C:\Users\Francis Maina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [21]:
 arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [22]:
#universal array functions

In [23]:
np.sqrt(arr) #squareroot

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [25]:
np.exp(arr) #exponential

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [26]:
np.max(arr)

10

In [29]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [30]:
np.log(arr)

C:\Users\Francis Maina\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [31]:
#check the official documentation of numpy Ufunc 

In [1]:
pwd

'C:\\Users\\Francis Maina'